name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        id: assign
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: bradhoekstra, jayantid, GinnyJI, dshnayder, stalhaali, toshiowang # if draft, assigned when draft is released
          max-num-of-reviewers: 1
          draft-keyword: wip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}' # success or failure
